version: '3.11'

services:
  web:
    build: .
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - .:/code
    environment:
      - DB_NAME=interactive_db
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - DB_HOST=db
      - DB_PORT=5432
      - HOST=db
      - DATABASE_URL=postgres://postgres:12345678@db:5432/interactive_db
    depends_on:
      - db
    command: >
      bash -c "urlwait &&
               pip install -r requirements.txt &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-12345678}
      - POSTGRES_DB=interactive_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  adminer:
    image: adminer:4.8.1
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=flat
      - ADMINER_PLUGINS=tables-filter
    ports:
      - 8040:8080

volumes:
    static_volume:
    media_volume:
    db:
